### ISSUE TITLE
Unable to read codeplug

### ISSUE THREAD

**Issue by greggawatt** [hmatuschek/qdmr#185]
I saved the following codeplug but now QDMR gives an error when trying to read
```
cat codeplug.yaml 
---
version: 0.9.3
settings:
  introLine1: Hack The
  introLine2: Planet!
  micLevel: 1
  speech: false
  power: High
  squelch: 1
  vox: 3
  tot: 0
  tyt:
    monitorType: Open
    allLEDsDisabled: false
    talkPermitToneDigital: false
    talkPermitToneAnalog: false
    passwordAndLock: false
    channelFreeIndicationTone: false
    allTonesDisabled: false
    powerSaveMode: true
    wakeupPreamble: true
    bootPicture: true
    txPreambleDuration: 600
    groupCallHangTime: 3000
    privateCallHangTime: 4000
    lowBatteryWarnInterval: 120
    callAlertToneContinuous: true
    callAlertToneDuration: 0
    loneWorkerResponseTime: 1
    loneWorkerReminderTime: 10
    digitalScanHangTime: 1000
    analogScanHangTime: 1000
    backlightAlwaysOn: false
    backlightDuration: 10
    keypadLockManual: true
    keypadLockTime: 1275
    powerOnPasswordEnabled: false
    powerOnPassword: 0
    radioProgPasswordEnabled: false
    radioProgPassword: 0
    pcProgPassword: Ã¿Ã¿Ã¿Ã¿Ã¿Ã¿Ã¿Ã¿
  defaultID: id1
radioIDs:
  - dmr: {id: id1, name: K6XSS, number: 3185656}
contacts:
  - dmr: {id: cont1, name: Justin KM6ZTH, ring: false, type: PrivateCall, number: 3177231}
  - dmr: {id: cont2, name: BAYAREA-DMR, ring: false, type: GroupCall, number: 311433}
  - dmr: {id: cont3, name: California, ring: false, type: GroupCall, number: 3106}
  - dmr: {id: cont4, name: CCFusion, ring: false, type: GroupCall, number: 310602}
  - dmr: {id: cont5, name: Parrot, ring: false, type: PrivateCall, number: 9990}
  - dmr: {id: cont6, name: NorCal 1, ring: false, type: GroupCall, number: 31069}
  - dmr: {id: cont7, name: NorCal, ring: false, type: GroupCall, number: 31068}
  - dmr: {id: cont8, name: World-wide, ring: false, type: GroupCall, number: 91}
  - dmr: {id: cont9, name: Disconnect, ring: false, type: GroupCall, number: 4000}
groupLists:
  []
channels:
  - digital:
      id: ch1
      name: K6MDD-NorCal
      rxFrequency: 144.975
      txFrequency: 147.475
      rxOnly: false
      tyt:
        loneWorker: false
        autoScan: false
        talkaround: false
        dataCallConfirmed: false
        privateCallConfirmed: false
        emergencyAlarmConfirmed: false
        displayPTTId: true
        rxRefFrequency: Low
        txRefFrequency: Low
        tightSquelch: false
        compressedUDPHeader: false
        reverseBurst: true
        killTone: Off
        inCallCriterion: Always
        allowInterrupt: false
        dcdm: false
        dcdmLeader: false
      admit: Always
      colorCode: 1
      timeSlot: TS2
      contact: cont7
      power: High
      timeout: 0
      vox: 0
  - digital:
      id: ch2
      name: K6MDD-Parrot
      rxFrequency: 144.975
      txFrequency: 147.475
      rxOnly: false
      tyt:
        loneWorker: false
        autoScan: false
        talkaround: false
        dataCallConfirmed: false
        privateCallConfirmed: false
        emergencyAlarmConfirmed: false
        displayPTTId: true
        rxRefFrequency: Low
        txRefFrequency: Low
        tightSquelch: false
        compressedUDPHeader: false
        reverseBurst: true
        killTone: Off
        inCallCriterion: Always
        allowInterrupt: false
        dcdm: false
        dcdmLeader: false
      admit: Always
      colorCode: 1
      timeSlot: TS1
      contact: cont5
      power: High
      timeout: 0
      vox: 0
  - digital:
      id: ch3
      name: PiStar-WW
      rxFrequency: 438.8
      txFrequency: 438.8
      rxOnly: false
      admit: Always
      colorCode: 1
      timeSlot: TS2
      radioId: id1
      contact: cont8
      power: Low
      timeout: !<!default> ""
      vox: !<!default> ""
  - digital:
      id: ch4
      name: PiStar-Parrot
      rxFrequency: 438.8
      txFrequency: 438.8
      rxOnly: false
      admit: Always
      colorCode: 1
      timeSlot: TS2
      radioId: id1
      contact: cont5
      power: Low
      timeout: !<!default> ""
      vox: !<!default> ""
  - digital:
      id: ch5
      name: PiStar-Disco
      rxFrequency: 438.8
      txFrequency: 438.8
      rxOnly: false
      admit: Always
      colorCode: 1
      timeSlot: TS2
      radioId: id1
      contact: cont9
      power: Low
      timeout: !<!default> ""
      vox: !<!default> ""
  - digital:
      id: ch6
      name: PiStar-BayArea
      rxFrequency: 438.8
      txFrequency: 438.8
      rxOnly: false
      admit: Always
      colorCode: 1
      timeSlot: TS2
      radioId: id1
      contact: cont2
      power: Low
      timeout: !<!default> ""
      vox: !<!default> ""
  - digital:
      id: ch7
      name: PiStar-Cali
      rxFrequency: 438.8
      txFrequency: 438.8
      rxOnly: false
      admit: Always
      colorCode: 1
      timeSlot: TS2
      radioId: id1
      contact: cont3
      power: Low
      timeout: !<!default> ""
      vox: !<!default> ""
  - digital:
      id: ch8
      name: PiStar-KM6ZTH
      rxFrequency: 438.8
      txFrequency: 438.8
      rxOnly: false
      admit: Always
      colorCode: 1
      timeSlot: TS2
      radioId: id1
      contact: cont1
      power: Low
      timeout: !<!default> ""
      vox: !<!default> ""
zones:
  - id: zone1
    name: K6MDD
    A: [ch1, ch2]
    B: []
  - id: zone2
    name: PiStar
    A: [ch3, ch4, ch5]
    B: []
tytExtension:
  buttonSettings:
    sideButton1Short: PowerSelect
    sideButton1Long: Disabled
    sideButton2Short: MonitorToggle
    sideButton2Long: Disabled
    longPressDuration: 1000
...
```

Gives the error `Cannot read codeplug from file '/home/gigawatt/codeplug.yaml': `
