### ISSUE TITLE
Frequency rounding error

### ISSUE THREAD

**Issue by endrec** [hmatuschek/qdmr#249]
Frequencies are converted to string with a small rounding error:

```
# [...]
channels:
# [...]
  - analog:
      id: ch14
      name: A-V16-145.2000
      rxFrequency: 145.19999999999999
      txFrequency: 145.19999999999999
      # [...]
  - analog:
      id: ch15
      name: A-V17-145.2125
      rxFrequency: 145.21250000000001
      txFrequency: 145.21250000000001
      # [...]
  - analog:
      id: ch16
      name: A-V18-145.2250
      rxFrequency: 145.22499999999999
      txFrequency: 145.22499999999999
      # [...]
  - analog:
      id: ch17
      name: A-V19-145.2375
      rxFrequency: 145.23750000000001
      txFrequency: 145.23750000000001
      # [...]
  - analog:
      id: ch18
      name: A-V20-145.2500
      rxFrequency: 145.25
      txFrequency: 145.25
# [...]
```

qdmr displays them correctly:
![image](https://user-images.githubusercontent.com/101801/189535705-b037c18e-ec9b-4570-ac2b-3ecaaf8cf840.png)

![image](https://user-images.githubusercontent.com/101801/189535637-a1243c7e-0d59-4395-9824-fa5b42e32482.png)

The issue does not seem to have any adverse effect so far, so it's only cosmetics. :)
Built from bc79685, and tested with AT878UV II.
