### ISSUE TITLE
Aprs on AT-D878UVII enabled as digital

### ISSUE THREAD

**Issue by majkrzak** [hmatuschek/qdmr#308]
I was programming my AT-D878UVII when encountered a problem with APRS config. When uploading to the radio, the `APRS -> Upload Type` got set to  `Sel D Aprs` which stands for uploading aprs via the DMR, AFAIK. In the official CPS this is named `APRS Report Type`.

```yaml
channels:
- analog:
    admit: Always
    aprs: aprs1
    id: APRS
    name: APRS
    power: Max
    rxFrequency: 144.8
    rxOnly: 'true'
    txFrequency: 144.8
positioning:
- aprs:
    destination: APAT81-0
    icon: Jogger
    id: aprs1
    message: ''
    name: APRS
    period: 0
    revert: APRS
    source: 3Z9V-0
 ```
