### ISSUE TITLE
[Anytone D878UVII+] Function Keys PF1-3 read wrong

### ISSUE THREAD

**Issue by smrqdt** [hmatuschek/qdmr#375]
qdmr 0.11.3 mixes up PF1, PF2 and PF3 key functions when reading from and re-writing to Anytone D878IV II Plus with firmware 3.02n.

## Steps to reproduce:
1. Program PF1-3 on device
2. read codeplug into qdmr from device
3. write codeplug back to device
4. observe changed key functions on device

| Key | before | after ||
|-----|---------|------|-|
| PF1 short | Slot Switch |  Off | `funcKeyAShort` |
| PF1 long | Digi Monitor | Encryption | `funcKeyALong` |
| PF2 short | Monitor | Voltage | `funcKeyBShort` |
| PF2 long | Off | Call | `funcKeyBLong` |
| PF3 short | TX Power | TX Power | `funcKeyCShort` |
| PF3 long | APRS Send | Vox | `funcKeyCLong` |

## Anytone CPS before using qdmr
![Keys_before_qdmr](https://github.com/hmatuschek/qdmr/assets/382221/77ff3b22-97d9-4cbc-aebc-e421003a9e85)

## qdmr codeplug
excerpt from yaml
```yaml
    keySettings:
      funcKey1Short: ToggleMainChannel
      funcKey1Long: SubChannel
      funcKey2Short: ToggleVFO
      funcKey2Long: ChannelType
      funcKey3Short: Power
      funcKey3Long: APRSSend
      funcKey4Short: Repeater
      funcKey4Long: SMS
      funcKey5Short: Reverse
      funcKey5Long: Dial
      funcKey6Short: Encryption
      funcKey6Long: Off
      funcKeyAShort: Off
      funcKeyALong: Encryption
      funcKeyBShort: Voltage
      funcKeyBLong: Call
      funcKeyCShort: Power
      funcKeyCLong: VOX
      funcKeyDShort: Off
      funcKeyDLong: Off
      longPressDuration: 2 s
      autoKeyLock: false
      knobLock: true
      keypadLock: true
      sideKeysLock: true
      forcedKeyLock: false
```

## Anytone CPS after programming with qdmr
![Keys_after_qdmr](https://github.com/hmatuschek/qdmr/assets/382221/6817d6a0-bbf9-42d6-a625-69e432662484)

I can provide the Anytone codeplugs before/after if useful.

## Versions

Anytone D878UVII Plus with Firmware 3.02n
qmdr 0.11.3
