### ISSUE TITLE
feature request: should be able to pre-set APRS location for SOTA

### ISSUE THREAD

**Issue by ec1oud** [hmatuschek/qdmr#551]
With the Windows codeplug editor I was able to preset APRS coordinates to transmit on a particular channel.  My DM1701 doesn't have GPS, but this provides a way to set up in advance to notify when I have reached a SOTA destination (and when I got back home, if that's the default position for the usual APRS channel).  I hear the reply packet on the APRS channel, and I verified that I show up on aprs.fi immediately afterwards.  But when I write the codeplug with qdmr, the radio prompts me with "Location?" when I hit the transmit button.  And I don't see how to set GPS coordinates in qdmr.  We have Source and Destination fields though.  Shouldn't the Source be my callsign by default?

Ideally it would be possible to comply with this specification: https://www.sotaspots.co.uk/Aprs2Sota_Info.php so that changing to my SOTA APRS channel and hitting the transmit button would amount to self-spotting.  (Of course testing the SOTA "channel" is some effort.  ;-) But I can test the usual channel that should have my home location as below.)

![Image](https://github.com/user-attachments/assets/2dc5677d-72f6-420d-b860-590648fcf392)

```
positioning:
  - aprs:
      id: aprs1
      name: Edelgnvn
      period: 0
      revert: ch17
      icon: Home
      message: ""
      destination: APN000-0
      source: -7
```

**Comment by hmatuschek** [comment]
The source call is just the name/callsign assigned to the default DMR Id (the one, that can be set in OpenGD77). The OpenGD77 firmware calls it "call sign" but it is actually the name of the radio. I've created sub-issue for that, but I cannot reproduce it. 

Further, you can actually set the fixed location for a channel. This should be encoded in a so-called device specific extension for that channel. There is a OpenGD77 channel extension (enable it in the settings dialog to see it) encoding the fixed location using a locator.

**Comment by hmatuschek** [comment]
However, there is a bug...

![Image](https://github.com/user-attachments/assets/6351ae17-4928-4395-b622-037ef339c777)

**Comment by ec1oud** [comment]
I see.  Well so far I can set a location, but the QTreeView delegate is truncating the ending character (it's w not v).  And the radio is still giving me a "Location ?" popup.

![Image](https://github.com/user-attachments/assets/916fb0af-1398-4e4c-866d-f598d85bc219)

**Comment by hmatuschek** [comment]
what about the source call? Did you set a name for your DMR ID? This is used as the radio name and OpenGD77 uses this as the source call for the APRS messages.

**Comment by ec1oud** [comment]
On the Settings tab, Radio Name is my callsign (LB2JK).  On the "APRS System" entry, Source is my callsign.  I don't know what Destination APN0000-0 means.  And the "channel" has the Rx/Tx frequencies being the same (where the digipeater is listening), and APRS selection is the one from the "APRS System" entry.

I'm trying to send a conventional APRS AX.25 FM packet, not via DMR.  But in the firmware the same "radio name" has to match?  Then it has to be the callsign actually, not some other radio name, right?  Because an APRS packet has to come from a callsign AFAIK.

In the yaml file, after I turned on the openGD77 extensions, every channel got a location, randomly or otherwise incorrect.  

```
      power: High
      timeout: !<!default> ""
      vox: 0
      squelch: !<!default> ""
  - analog:
      id: ch2
      name: Drammen UHF
      rxOnly: false
      openGD77:
        scanZoneSkip: false
        scanAllSkip: false
        beep: true
        powerSave: true
        location: II90wa
        talkerAliasTS1: None
        talkerAliasTS2: None
      admit: Always
      rxTone: ~
      txTone:
        ctcss: 110.9 Hz
      bandwidth: Narrow
      rxFrequency: 434.725 MHz
      txFrequency: 432.725 MHz
      power: High
      timeout: !<!default> ""
      vox: 0
      squelch: !<!default> ""
...
```

Maybe it doesn't matter if it's not an APRS channel, but what does it mean then?

I also had several DMR IDs; not sure why.  I tried removing all but the first one by hand just now.

```
settings:
  introLine1: LB2JK
  introLine2: ...
  micLevel: 3
  speech: false
  power: Low
  squelch: 1
  vox: 0
  tot: 0
  defaultID: id1
radioIDs:
  - dmr: {id: id1, name: LB2JK, number: 2420532}
  - dmr: {id: id2, name: Unknown ID, number: 242650}
  - dmr: {id: id3, name: Unknown ID, number: 242101}
  - dmr: {id: id4, name: Unknown ID, number: 91}
  - dmr: {id: id5, name: Unknown ID, number: 242102}
  - dmr: {id: id6, name: Unknown ID, number: 242002}
contacts:
  - dmr: {id: cont1, name: Local 9, ring: false, type: GroupCall, number: 9, openGD77: {timeSlotOverride: None}}
```
